"""atd-client — reference Python SDK for the Agent Tool Dispatch protocol."""

from atd_client.client import AtdClient
from atd_client.errors import (
    AtdError,
    BindingUnavailable,
    CapabilityDenied,
    InvalidArguments,
    NotImplementedFeature,
    ProtocolError,
    ServerUnreachable,
    Timeout,
    ToolExecutionFailed,
    ToolNotFound,
)
from atd_client.types import (
    BindingProtocol,
    SafetyLevel,
    ToolBinding,
    ToolCapability,
    ToolDefinition,
    ToolFailure,
    ToolResources,
    ToolResult,
    ToolResultMetadata,
    ToolSafety,
    ToolSuccess,
    ToolSummary,
    ToolTier,
    ToolTrust,
    ToolVisibility,
    TrustLevel,
)

__version__ = "0.1.0"

__all__ = [
    "AtdClient",
    "AtdError",
    "BindingProtocol",
    "BindingUnavailable",
    "CapabilityDenied",
    "InvalidArguments",
    "NotImplementedFeature",
    "ProtocolError",
    "SafetyLevel",
    "ServerUnreachable",
    "Timeout",
    "ToolBinding",
    "ToolCapability",
    "ToolDefinition",
    "ToolExecutionFailed",
    "ToolFailure",
    "ToolNotFound",
    "ToolResources",
    "ToolResult",
    "ToolResultMetadata",
    "ToolSafety",
    "ToolSuccess",
    "ToolSummary",
    "ToolTier",
    "ToolTrust",
    "ToolVisibility",
    "TrustLevel",
    "__version__",
]
